application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  license.accept:
    type: string
    title: EULA License
    description: Accept EULA license
    default: "no"
  cic.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  nsIP:
    type: string
    title: NS IP of the VPX
    description: NS IP of the VPX
  nsVIP:
    type: string
    title: Virtual IP of the VPX
    description: Virtual IP of the VPX
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: "These Permission are required for configuring Citrix ADC VPX according to the current state of the Kubernetes Cluster"
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["endpoints", "ingresses", "pods", "secrets", "routes", "nodes", "namespaces", "configmaps"]
            verbs: ["get", "list", "watch"]
          - apiGroups: [""]
            resources: ["services/status"]
            verbs: ["patch"]
          - apiGroups: [""]
            resources: ["services"]
            verbs: ["get", "list", "watch", "patch"]
          - apiGroups: [""]
            resources: ["events"]
            verbs: ["create"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses", "ingressclasses"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses/status"]
            verbs: ["patch"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["apps"]
            resources: ["deployments"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["citrix.com"]
            resources: ["rewritepolicies", "continuousdeployments", "authpolicies", "ratelimits", "listeners", "httproutes", "wafs", "apigatewaypolicies", "bots"]
            verbs: ["get", "list", "watch", "create", "delete", "patch"]
          - apiGroups: ["citrix.com"]
            resources: ["rewritepolicies/status", "continuousdeployments/status", "authpolicies/status", "ratelimits/status", "listeners/status", "httproutes/status", "wafs/status", "apigatewaypolicies/status", "bots/status"]
            verbs: ["get", "list", "patch"]
          - apiGroups: ["citrix.com"]
            resources: ["vips"]
            verbs: ["get", "list", "watch", "create", "delete"]
          - apiGroups: ["crd.projectcalico.org"]
            resources: ["ipamblocks"]
            verbs: ["get", "list", "watch"]
  adcCredentialSecret:
    type: string
    title: Secret file Name for Citrix ADC
    description: Secret file Name for Citrix ADC
  nsPort:
    type: integer
    title: NITRO port
    description: nsPort is port for Citrix ADC NITRO
    default: 443
  nsProtocol:
    type: string
    title: protocol for NITRO
    description: protocol used for NetScaler ADC NITRO
    default: HTTPS
  logLevel:
    type: string
    title: Log level of Citrix ingress controller
    description: Level of logs generated by Citrix ingress controller
    default: DEBUG
  ingressClass:
    type: string
    title: Ingress Class
    description: Please provide name of the Ingress Class.
  nodeWatch:
    type: boolean
    title: Automatic route configuration
    description: Automatic route configuration on Citrix ADC VPX towards the pod network
    default: false
  exporter.image:
    type: string
    default: $REGISTRY/citrix-adc-metrics-exporter:$TAG
    x-google-marketplace:
      type: IMAGE
  exporter.required:
    type: boolean
    title: Prometheus Exporter
    description: Set if exporter is needed with Citrix ADC CPX
    default: false
  exporter.ports.containerPort:
    type: integer
    title: Prometheus Exporter Port
    description: Specify on which port metrics collected by the exporter should be exposed.
    default: 8888

required:
- name
- namespace
- serviceAccount
- cic.image
- nsIP
- exporter.required
- exporter.image
