properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE
  nsIP:
    type: string
    default: 1.1.1.1
  adcCredentialSecret:
    type: string
    default: nslogin
  
