apiVersion: v1
kind: Secret
metadata:
    name: nslogin
    labels:
      app: cic-k8s-secret
      app.kubernetes.io/name: "{{ .Release.Name }}"
type: Opaque
data:
    username: bnNyb290
    password: bnNyb290

